version: "3.7"

services:
  apache2:
    image: ubuntu/apache2:2.4-22.04_beta
    container_name: con_ap_apache2
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./apache2:/etc/apache2
      - ./certs:/etc/certs
      - ./www:/var/www
      - ./log/apache2:/var/log/apache2
    working_dir: /var/www
  php82:
    image: trongtayninh/php:8.2
    container_name: con_ap_php8.2
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./www:/var/www
      - ./php8.2/php.ini:/usr/local/etc/php/php.ini
      - ./php8.2/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www